services:
  - type: web
    name: ev-wpt-api
    runtime: python
    plan: free
    buildCommand: "pip install -r ml/requirements.txt -r webdev/backend/requirements.txt && cd ml && python get_data.py && python train.py"
    startCommand: "cd webdev/backend && uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.9"
      - key: DATABASE_URL
        sync: false
      - key: THINGSPEAK_CHANNEL
        sync: false
      - key: THINGSPEAK_READ_KEY
        sync: false
